version: 2.1

orbs:
  bitcart: bitcart/bitcart-shared@2

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - bitcart/lint:
          name: lint
          executor: bitcart/python-node
          pre-steps:
            - checkout
            - bitcart/install-node-dependencies
