version: 2.1

orbs:
  bitcartcc: bitcartcc/bitcartcc-shared@1

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - bitcartcc/lint:
          name: lint
          executor: bitcartcc/python-node
          pre-steps:
            - checkout
            - bitcartcc/install-node-dependencies
